"""fix_missing_wanted_list_reason_and_user_fields

Revision ID: c497879eb940
Revises: 43bdada2911f
Create Date: 2026-05-15 15:49:41.900324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c497879eb940'
down_revision = '43bdada2911f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_face_logs', schema=None) as batch_op:
        batch_op.alter_column('confidence_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_column('face_snapshot_url')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('old_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('new_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('customer_purchase_patterns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('total_quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('avg_quantity', sa.Float(), nullable=False))
        batch_op.drop_constraint('customer_purchase_patterns_customer_id_category_id_combinat_key', type_='unique')
        batch_op.create_unique_constraint(None, ['customer_id', 'item_id', 'category_id', 'combination_id'])
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['item_id'])

    with op.batch_alter_table('prescription_ocr_logs', schema=None) as batch_op:
        batch_op.alter_column('raw_extracted_text',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('parsed_medicines',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('verified_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('b2b_credentials',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('face_embedding', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('last_face_scan_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('wanted_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wanted_list', schema=None) as batch_op:
        batch_op.drop_column('reason')
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.drop_column('last_face_scan_at')
        batch_op.drop_column('face_embedding')
        batch_op.drop_column('title')

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('b2b_credentials',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('prescription_ocr_logs', schema=None) as batch_op:
        batch_op.alter_column('verified_by',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('parsed_medicines',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('raw_extracted_text',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('customer_purchase_patterns', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('customer_purchase_patterns_customer_id_category_id_combinat_key', ['customer_id', 'category_id', 'combination_id'])
        batch_op.drop_column('avg_quantity')
        batch_op.drop_column('total_quantity')
        batch_op.drop_column('item_id')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('new_value',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('old_value',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('ai_face_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_snapshot_url', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('confidence_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
